package arenaiq.encaminhador.evento.core.models;

public enum EMotivo {
  MANTER_POSSE, TRABALHAR_JOGADA, VIRAR_JOGO, TABELA_SIMPLES,
  TABELA_ELABORADA, LACAMENTO, CRUZAMENTO, CONTRA_ATAQUE,
  EVITAR_GOL, TENTAR_GOL, PRESSIONAR, TRABALHAR_ERRO,
  SEGURAR_JOGO, MATAR_ATAQUE, FAZER_FALTA, ROUBAR_BOLA
}
