server:
  port: 63103

spring:
  data:
    neo4j:
      uri: bolt://localhost:56870
      username: neo4j
      password: password

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      recebidor-sucess: recebidor-jogador-sucess
      recebidor-fail: recebidor-jogador-fail
      persistence-fail: persistence-jogador-fail
      notify-ending: notify-ending
    consumer:
      group-id: recebidor-jogador-group
      auto-offset-reset: latest
