server:
  port: 63001
 
spring:
  data:
    mongodb:
      uri: mongodb://encaminhador:encaminhador@localhost:61000/encaminhador-db
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      encaminhador-eventos-start: encaminhador-evento-start
    consumer:
      group-id: encaminhador-evento-group
      auto-offset-reset: latest