server:
  port: ${SERVER_PORT:60007}

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://soccervs:soccervs@localhost:55100}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      linha-defensiva-start: linha-defensiva-start
      linha-defensiva-ending: linha-defensiva-ending
      
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest