server:
  port: 63201
 
spring:
  data:
    mongodb:
      uri: mongodb://datalake:datalake@localhost:61000/datalake
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      eventos-start: eventos-start
      notify-ending: notify-ending
    consumer:
      group-id: persistencia-group
      auto-offset-reset: latest