package arenaiq.encaminhador.evento.core.models.enums;

public enum EEvento {
  PASSE_CURTO_RASTEIRO, PASSE_MEDIO_RASTEIRO, PASSE_LONGO_RASTEIRO,
  PASSE_CURTO_RASANTE, PASSE_MEDIO_RASANTE, PASSE_LONGO_RASANTE,
  PASSE_CURTO_ALTO, PASSE_MEDIO_ALTO, PASSE_LONGO_ALTO,

  DEFESA_FACIL, DEFESA_MEDIA, DEFESA_DIFICIL, DEFESA_IMPOSSIVEL,
  PRESSAO_ALTA, PRESSAO_MEDIA, PRESSAO_BAIXA,

  CHUTE_CURTO_RASTEIRO, CHUTE_MEDIO_RASTEIRO, CHUTE_LONGO_RASTEIRO,
  CHUTE_CURTO_RASANTE, CHUTE_MEDIO_RASANTE, CHUTE_LONGO_RASANTE,
  CHUTE_CURTO_ALTO, CHUTE_MEDIO_ALTO, CHUTE_LONGO_ALTO,

  GOL, GOL_CABECA, GOL_VOLEIO, GOL_FALTA, GOL_ESCANTEIO, GOL_PENALTI,

  CARRINHO_CURTO, CARRINHO_MEDIO, CARRINHO_LONGO,
  BOTE_CURTO, BOTE_MEDIO
}
