---
title: "Machine Learning e Alertas Inteligentes"
---

Objetivo: Criar alertas automáticos para detectar padrões de risco ou sucesso.

Campos para cruzar:

    Todos os de eventos, formações, linhas

    desempenho histórico, resultado final, placar parcial

    clima, temperatura, umidade

    jogadores em campo, função, posição

    tecnico, estilo, pressão adversária


```{r}
#library(mongolite)

uri <- "mongodb://datalake:datalake@localhost:61000/datalake"

# Selecionar uma collection (por exemplo, "Eventos")
eventos <- mongo(collection = "Eventos", db = "datalake", url = uri)

# Depois, para "Formacoes"
formacoes <- mongo(collection = "Formacoes", db = "datalake", url = uri)

# E para "Linhas"
linhas <- mongo(collection = "Linhas", db = "datalake", url = uri)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
