server:
  port: 63202
 
spring:
  data:
    cassandra:
      keyspaceName: arenaiq-datalake
      contactPoints: localhost
      port: 60000
      schemaAction: CREATE_IF_NOT_EXISTS
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      eventos-start: eventos-start
      notify-ending: notify-ending
    consumer:
      group-id: persistencia-group
      auto-offset-reset: latest