server:
  port: ${SERVER_PORT:60008}

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://soccervs:soccervs@localhost:55100}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      movimentacao-start: movimentacao-start
      movimentacao-ending: movimentacao-ending
      
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest