package arenaiq.persistencia.evento.core.models;

public enum EAtor {
  //EQUIPE
  EGOLEIRO,
  EDEFENSOR_DIREITO, EDEFENSOR_CENTRAL, EDEFENSOR_ESQUERDO,
  ELATERAL_DIREITO, ELATERAL_ESQUERDO,
  EVANCADO_DIREITO, EVANCADO_ESQUERDO,
  EVOL_DIREITO, EVOL_CENTRAL, EVOL_ESQUERDO,
  EMEDIO_DIREITO, EMEDIO_CENTRAL, EMEDIO_ESQUERDO,
  EMEIA_DIREITO, EMEIA_CENTRAL, EMEIA_ESQUERDO,
  EPONTA_DIREITO, EPONTA_ESQUERDO,
  EATACANTE_DIREITO, EATACANTE_CENTRAL, EATACANTE_ESQUERDO,
  //ADVERSARIO
  AGOLEIRO,
  ADEFENSOR_DIREITO, ADEFENSOR_CENTRAL, ADEFENSOR_ESQUERDO,
  ALATERAL_DIREITO, ALATERAL_ESQUERDO,
  AVANCADO_DIREITO, AVANCADO_ESQUERDO,
  AVOL_DIREITO, AVOL_CENTRAL, AVOL_ESQUERDO,
  AMEDIO_DIREITO, AMEDIO_CENTRAL, AMEDIO_ESQUERDO,
  AMEIA_DIREITO, AMEIA_CENTRAL, AMEIA_ESQUERDO,
  APONTA_DIREITO, APONTA_ESQUERDO,
  AATACANTE_DIREITO, AATACANTE_CENTRAL, AATACANTE_ESQUERDO
}
