server:
  port: ${SERVER_PORT:61000}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.200:55000/soccervs-persistence
    username: soccervs
    password: soccervs
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
   bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
   topic:
     inventory-success: inventory-success
     inventory-fail: inventory-fail
     payment-fail: payment-fail
     notify-ending: notify-ending
   consumer:
     group-id: payment-group
     auto-offset-reset: latest