server:
  port: ${SERVER_PORT:60000}

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://soccervs:soccervs@localhost:55100}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      formacao-time-start: formacao-time-start
      formacao-time-ending: formacao-time-ending
      
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest