server:
  port: ${SERVER_PORT:60000}

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://soccervs:soccervs@localhost:55100}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      persistence-start: persistence-start
      notify-ending: notify-ending
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest