server:
  port: ${SERVER_PORT:60000}

spring:
  data:
    mongodb:
      database: admin
      uri: ${MONGO_DB_URI:mongodb://soccervs:soccervs@localhost:55100}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      cartoes-start: cartoes-start
      cartoes-ending: cartoes-ending
      eventos-especificos-start: eventos-especificos-start
      eventos-especificos-ending: eventos-especificos-ending
      faltas-start: faltas-start
      faltas-ending: faltas-ending
      finalizacoes-start: finalizacoes-start
      finalizacoes-ending: finalizacoes-ending
      formacao-time-start: formacao-time-start
      formacao-time-ending: formacao-time-ending
      linha-defensiva-start: linha-defensiva-start
      linha-defensiva-ending: linha-defensiva-ending
      movimentacao-start: movimentacao-start
      movimentacao-ending: movimentacao-ending
      passes-detalhes-start: passes-detalhes-start
      passes-detalhes-ending: passes-detalhes-ending
      relacao-jogadores-start: relacao-jogadores-start
      relacao-jogadores-ending: relacao-jogadores-ending
    consumer:
      group-id: persistence-group
      auto-offset-reset: latest