server:
  port: 63102

spring:
  data:
    neo4j:
      uri: bolt://localhost:56870
      username: neo4j
      password: password

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      eventos-start: recebidor-formacao-start
      notify-ending: notify-ending
    consumer:
      group-id: recebidor-formacao-group
      auto-offset-reset: latest