server:
  port: 50000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:55000/soccervs_persistence
    username: soccervs
    password: soccervs
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true