version: '3.8'

services:
  arenaiq-partida:
    image: mongo:6.0
    container_name: arenaiq-partida
    restart: always
    ports:
      - "61001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: partida
      MONGO_INITDB_ROOT_PASSWORD: partida
    networks:
      - arenaiq-network

  arenaiq-treino:
    image: mongo:6.0
    container_name: arenaiq-treino
    restart: always
    ports:
      - "61000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: treino
      MONGO_INITDB_ROOT_PASSWORD: treino
    networks:
      - arenaiq-network

  arenaiq-encaminhador:
    image: mongo:6.0
    container_name: arenaiq-encaminhador
    restart: always
    ports:
      - "61002:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: encaminhador
      MONGO_INITDB_ROOT_PASSWORD: encaminhador
    networks:
      - arenaiq-network

  arenaiq-recebidor:
    image: mongo:6.0
    container_name: arenaiq-recebidor
    restart: always
    ports:
      - "61003:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: recebidor
      MONGO_INITDB_ROOT_PASSWORD: recebidor
    networks:
      - arenaiq-network

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    restart: always
    ports:
      - "60000:9042"
    environment:
      - CASSANDRA_KEYSPACE=arenaiq-datalake
    networks:
      - arenaiq-network

volumes:
  cassandra:
  arenaiq-recebidor:
  arenaiq-encaminhador:
  arenaiq-treino:
  arenaiq-partida:

networks:
  arenaiq-network:
    driver: bridge
