version: '3.8'

services:
  arenaiq-mongo:
    image: mongo:6.0
    container_name: arenaiq-mongo
    restart: always
    ports:
      - "61000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    command: ["mongod", "--bind_ip", "0.0.0.0"]
    networks:
      - arenaiq-network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  cassandra:
    image: cassandra:4.1
    container_name: arenaiq-datalake
    restart: always
    ports:
      - "60000:9042"
    environment:
      - CASSANDRA_KEYSPACE=arenaiq-datalake
    networks:
      - arenaiq-network

volumes:
  mongo_data:
  cassandra:

networks:
  arenaiq-network:
    driver: bridge
