version: "3.8"

services:
  mariadb-persistence:
    image: mariadb:latest
    container_name: soccervs-persistence
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: persistence
      MARIADB_DATABASE: soccervs_persistence
      MARIADB_USER: soccervs
      MARIADB_PASSWORD: soccervs
    ports:
      - "55000:3306"  # Só precisa expor se for acessado fora do Docker
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - soccervs

  mongodb-reciever:
    image: mongo:latest
    container_name: soccervs-reciever
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soccervs
      MONGO_INITDB_ROOT_PASSWORD: soccervs
    ports:
      - "55100:27017"
    volumes:
      - mongodb_reciever_data:/data/db
    networks:
      - soccervs

  mongodb-pitches:
    image: mongo:latest
    container_name: soccervs-pitches 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soccervs
      MONGO_INITDB_ROOT_PASSWORD: soccervs
    ports:
      - "55110:27017"
    volumes:
      - mongodb_pitches_data:/data/db
    networks:
      - soccervs

  mongodb-analitics:
    image: mongo:latest
    container_name: soccervs-analitics
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soccervs
      MONGO_INITDB_ROOT_PASSWORD: soccervs
    ports:
      - "55120:27017"
    volumes:
      - mongodb_analitics_data:/data/db
    networks:
      - soccervs

volumes:
  mariadb_data:
  mongodb_reciever_data:
  mongodb_pitches_data:
  mongodb_analitics_data:

networks:
  soccervs:
    driver: bridge
