server:
  port: 63206

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/arenaiq_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      persistencia-movimentacao-start: persistencia-partida-start
      notify-ending: notify-ending
    consumer:
      group-id: persistencia-partida-group
      auto-offset-reset: latest