package arenaiq.dadoshistoricos.core.models.enums;

public enum EFuncao {
  PAREDAO, MARCACAO, ULTIMA_LINHA, BATE_CARTEIRA, FORCA_FISICA,
  RABISCANTE, BOLA_PARADA, INCANSAVEL, CRUZAMENTO,
  CHUTA_LONGE, ATAQUE_AEREO, IMPIPOCAVEL
}
