server:
  port: 63003
 
spring:
  data:
    mongodb:
      uri: mongodb://encaminhador:encaminhador@localhost:61000/encaminhador-db
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      encaminhador-jogador-start: encaminhador-jogador-start
      notify-ending: notify-ending
    consumer:
      group-id: encaminhador-jogador-group
      auto-offset-reset: latest