server:
  port: 62000

spring:
  data:
    mongodb:
      uri: mongodb://partida:partida@localhost:61000/partida-db
    cassandra:
        keyspaceName: arenaiq-datalake
        contactPoints: localhost
        port: 60000
        schemaAction: CREATE_IF_NOT_EXISTS