server:
  port: 62000

spring:
  data:
    mongodb:
      uri: mongodb://datalake:datalake@localhost:61000/datalake
  
  datasource:
    url: jdbc:postgresql://localhost:54320/arenaiq_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect