server:
  port: 63002
 
spring:
  data:
    mongodb:
      uri: mongodb://encaminhador:encaminhador@localhost:61000/encaminhador-db
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      encaminhador-formacao-start: encaminhador-formacao-start
      notify-ending: notify-ending
    consumer:
      group-id: encaminhador-formacao-group
      auto-offset-reset: latest